title: Reynolds World Theme Demo
author:
  name: Mike Reynolds
  email: mike@example.com
  avatar: /assets/avatar.png
  bio: >-
    A demonstration site for the Reynolds World theme. This shows sample posts
    and pages to help you visualize your content.

description: >
  A demonstration site for the Reynolds World theme. This shows sample posts
  and pages to help you visualize your content.

theme: reynolds-world-theme
google_analytics: G-SOME_TEST_TOKEN

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import, division]
